import { Brand, Schema } from "effect"

// ---- branded primitives ----
//
// Nominal brands for the domain's string identifiers. `Brand.nominal`
// constructs them (compile-time separation, zero runtime cost — no format
// to validate: ids are opaque handles resolved at use sites). The
// `*Schema` values are built with `Schema.fromBrand`, which applies the
// constructor's brand tag to a string schema, so schema decodes at
// message/persistence boundaries produce exactly the branded type the
// constructor produces.

// ---- LayerId ----

/** Branded layer identifier (generated by `nextLayerId`). */
export type LayerId = string & Brand.Brand<"LayerId">

export const LayerId = Brand.nominal<LayerId>()

/** Decodes a string into a `LayerId` at schema boundaries. */
export const LayerIdSchema = Schema.fromBrand("LayerId", LayerId)(Schema.String)

// ---- LutId ----

/** Branded LUT library reference (a vendored `.cube` file path). */
export type LutId = string & Brand.Brand<"LutId">

export const LutId = Brand.nominal<LutId>()

/** Decodes a string into a `LutId` at schema boundaries. */
export const LutIdSchema = Schema.fromBrand("LutId", LutId)(Schema.String)

// ---- FieldKey ----

/** Branded field key on a layer (e.g. "stops", "amount"). */
export type FieldKey = string & Brand.Brand<"FieldKey">

export const FieldKey = Brand.nominal<FieldKey>()

/** Decodes a string into a `FieldKey` at schema boundaries. */
export const FieldKeySchema = Schema.fromBrand("FieldKey", FieldKey)(Schema.String)
